#!/bin/bash

## Description: Run phpcbf
## Usage: phpcbf [flags] [args]
## Example: "ddev phpcbf web/modules/custom"

TOP_LEVEL="/var/www/html"
cd $TOP_LEVEL

echo "--------------"
echo "Running PHPCBF"
echo "--------------"

vendor/bin/phpcbf --standard="Drupal,DrupalPractice" --extensions="php,module,inc,install,test,profile,theme,info,yml,css,js,txt,md,twig " $@ || \
echo "Return code ignored"

