#!/usr/bin/env bash

## Description: SetUp PHPUnit tests inside the web container.
## Usage: phpunit-setup
## Example: "ddev phpunit-setup"

# Set Simple test variables and put PHPUnit config in place.
PHPUNIT_CONFIG=/var/www/html/phpunit.xml

if [ -f "$PHPUNIT_CONFIG" ]; then
  cp phpunit.xml phpunit.xml.bak
  rm "$PHPUNIT_CONFIG"
fi

cd /var/www/html
cp -n web/core/phpunit.xml.dist "$PHPUNIT_CONFIG"
sed -i 's|tests\/bootstrap\.php|./web/core/tests/bootstrap.php|g' "$PHPUNIT_CONFIG"
sed -i 's|\.\/tests\/|./web/core/tests/|g' "$PHPUNIT_CONFIG"
sed -i 's|directory>\.\/|directory>./web/core/|g' "$PHPUNIT_CONFIG"
sed -i 's|directory>\.\.\/|directory>./web/core/|g' "$PHPUNIT_CONFIG"
# Set the base URL for kernel tests.
sed -i -e "s|name=\"SIMPLETEST_BASE_URL\" value=\"\"|name=\"SIMPLETEST_BASE_URL\" value=\"$DDEV_HOSTNAME\"|g" "$PHPUNIT_CONFIG"
sed -i 's|name="SIMPLETEST_DB" value=""|name="SIMPLETEST_DB" value="${PHPUNIT_DB_DRIVER}://${PHPUNIT_USER}:${PHPUNIT_PASSWORD}@${PHPUNIT_HOSTNAME}/${PHPUNIT_DATABASE}"|g' "$PHPUNIT_CONFIG"
sed -i 's|name="BROWSERTEST_OUTPUT_DIRECTORY" value=""|name="BROWSERTEST_OUTPUT_DIRECTORY" value="/var/www/html/web/sites/simpletest/browser_output"|g' "$PHPUNIT_CONFIG"
sed -i 's|<file>.\/web\/core\/tests\/TestSuites\/UnitTestSuite.php<\/file>|<directory>.\/web\/modules\/custom\/*\/tests\/src\/Unit<\/directory>|g' "$PHPUNIT_CONFIG"
sed -i 's|<file>.\/web\/core\/tests\/TestSuites\/KernelTestSuite.php<\/file>|<directory>.\/web\/modules\/custom\/*\/tests\/src\/Kernel<\/directory>|g' "$PHPUNIT_CONFIG"
sed -i 's|<file>.\/web\/core\/tests\/TestSuites\/FunctionalTestSuite.php<\/file>|<directory>.\/web\/modules\/custom\/*\/tests\/src\/Functional<\/directory>|g' "$PHPUNIT_CONFIG"
sed -i 's|<file>.\/web\/core\/tests\/TestSuites\/FunctionalJavascriptTestSuite.php<\/file>|<directory>.\/web\/modules\/custom\/*\/tests\/src\/FunctionalJavascript<\/directory>|g' "$PHPUNIT_CONFIG"
sed -i '/<file>.\/web\/core\/tests\/TestSuites\/BuildTestSuite.php<\/file>/d' "$PHPUNIT_CONFIG"
/var/www/html/vendor/bin/phpunit --migrate-configuration

rm phpunit.xml.bak
