#!/bin/bash

## Description: Run drupal rector on a specific module.
## Usage: rector MODULE_PATH [-d|--dry-run]
## Example: "ddev rector web/modules/contrib/admin_toolbar" or "ddev rector web/modules/contrib/admin_toolbar -d"

if [ $# -eq 0 ]
then
  echo "You must specify a module path; e.g. 'ddev rector web/modules/contrib/admin_toolbar'"
  exit
fi

TOP_LEVEL="/var/www/html"
cd $TOP_LEVEL

if [ $# -eq 2 ]
then
  DRYRUN="--dry-run"
  if [ "$1" != "-d" ] && [ "$1" != "--dry-run" ]
  then
    MODULE_PATH="$1"
  else
    MODULE_PATH="$2"
  fi
else
  MODULE_PATH="$1"
  DRYRUN=""
fi

if [ ! -d "$MODULE_PATH" ]
then
  echo "The specified module [$MODULE_PATH] does not exist."
  exit
fi

echo "===================="
echo "Running rector with: $MODULE_PATH $DRYRUN"
echo "===================="
vendor/bin/rector process $MODULE_PATH $DRYRUN
